run:
  tests: true
  build-tags:
    - golangci
  allow-parallel-runners: true

issues:
  exclude-dirs:
    - .github
    - .vscode

output:
  sort-results: true

linters:
  enable-all: true
  disable:
  # Remove unsupported linters (deprecated and deactivated linters)
  #- scopelint
  #- deadcode
  #- nosnakecase
  #- exhaustivestruct
  #- varcheck
  #- golint
  #- ifshort
  #- interfacer
  #- maligned
  #- structcheck
  #
  # Disable deprecated/abandoned linters
  - execinquery
  - gomnd
  - exportloopref
  # Disabled because of generics
  - rowserrcheck
  - sqlclosecheck
  - wastedassign
  # Disable due to mock private functions
  - testpackage
  # Disable due to use of non-standard packages
  - depguard

linters-settings:
  cyclop:
    # The maximal code complexity to report (Default: 10).
    max-complexity: 15