name: Basic Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  platform-test:
    name: Platform test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1'
          check-latest: true
      - name: Run unit test
        run: go test -race -v ./...

  min-ver:
    name: Min supported go version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull docker image of min supported version of Go
        run: docker pull golang:1.23.0-alpine
      - name: Run tests on docker
        run: docker run --rm -v "$(pwd)":/workspace -w /workspace golang:1.22.0-alpine go test -timeout 30s -v ./...

  latest-ver:
    name: Latest go version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull latest docker image of Go
        run: docker pull golang:alpine
      - name: Run tests on docker
        run: docker run --rm -v "$(pwd)":/workspace -w /workspace golang:alpine go test -timeout 30s -v ./...
